apiVersion: v1
kind: Service
metadata:
  name: dev-deployment-service
spec:
  type: LoadBalancer
  selector:
    app: dev-app
  ports:
  - port: 8080      # Porta em que o serviço estará acessível externamente
    targetPort: 8080 # Porta em que o contêiner está ouvindo (conforme definido no Dockerfile)
